=== cesko-digital/volebni-kalkulacka-2022/schemas/calculator.schema.json
{
  "title": "calculator",
  "$id": "https://kalkulacka.ceskodigital.net/schemas/calculator.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A representation single calculator",
  "type": "object",
  "required": [
    "id",
    "name",
    "description",
    "district_code",
    "election",
    "questions",
    "candidates",
    "answers"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "UUID"
    },
    "name": {
      "type": "string",
      "description": "Election's name"
    },
    "description": {
      "type": "string",
      "description": "Longer description"
    },
    "district_code": {
      "type": "string"
    },
    "on_hp_from": {
      "type": "string",
      "description": "Show on HP start - ISO 8601"
    },
    "on_hp_to": {
      "type": "string",
      "description": "Show on HP end - ISO 8601"
    },
    "election": {
      "$ref": "https://kalkulacka.ceskodigital.net/schemas/election.schema.json"
    },
    "questions": {
      "type": "array",
      "description": "List of questions",
      "items": {
        "$ref": "https://kalkulacka.ceskodigital.net/schemas/question.schema.json"
      }
    },
    "candidates": {
      "type": "array",
      "description": "List of candidates",
      "items": {
        "$ref": "https://kalkulacka.ceskodigital.net/schemas/candidate.schema.json"
      }
    },
    "answers": {
      "type": "array",
      "description": "List of answers",
      "items": {
        "$ref": "https://kalkulacka.ceskodigital.net/schemas/candidate-answer.schema.json"
      }
    }
  }
}

=== cesko-digital/volebni-kalkulacka-2022/data/kalkulacka/komunalni-2022/569810.json
{
  "id": "komunalni-2022-569810",
  "name": "Hradec Králové",
  "description": "Hradec Králové - DESCRIPTION",
  "district_code": "569810",
  "election": {
    "id": "komunalni-2022",
    "key": "komunalni-2022",
    "name": "komunalni-2022",
    "description": "komunalni-2022"
  },
  "questions": [
    {
      "id": "komunalni-2022-569810-question-1",
      "name": "Gentrifikace",
      "title": "V žádaných městských částech mají bydlet jen ti, kdo si to mohou finančně dovolit.",
      "gist": "Kritikům vadí, že ekonomické tlaky na původní obyvatele vedou k jejich postupnému vytlačování. Městské části pak ztrácejí pestrost a uzavírají se jen pro vybrané skupiny lidí. Zastánci tvrdí, že to je přirozený proces a že na bydlení v dobré čtvrti si člověk musí vydělat.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-2",
      "name": "Poplatek za popelnice",
      "title": "Má město účtovat poplatek za svoz komunálního odpadu?",
      "gist": "Odpůrci tento poplatek považují za zbytečný; jedná se podle nich jen o jakousi „skrytou“ daň. Zastánci poplatku odmítají takový zásah do rozpočtu města na úkor důležitějších položek, přenesením zátěže na město.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-3",
      "name": "Omezení vytápění",
      "title": "Mělo by město v případě nouze začít omezovat vytápění v domovech pro seniory?",
      "gist": "Zastánci omezování tvrdí, že nejen domácnosti, ale i samosprávy mohou mít potíže hradit výdaje za teplo kvůli velkému růstu cen energií. Odpůrci namítají, že senioři jsou zranitelná skupina obyvatel a nesmí být vystaveni ohrožení zdraví ani ve stavu nouze.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-4",
      "name": "Zóny 30 km/h",
      "title": "Měly by se ve městě rozšířit zóny, kde mají auta povoleno jet max 30 km/h.?",
      "gist": "Obecně platí, že v obci smí vozidlo jet maximálně rychlostí 50 km/h. Zóny 30 (km/h) jsou podle zastánců levné opatření pro zklidňování dopravy v městské zástavbě a v některých evropských zemích se používají více než 20 let. Odpůrci to považují za brždění provozu a komplikaci dopravy.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-5",
      "name": "Milostivé léto",
      "title": "Právě probíhá akce Milostivé léto: Má město individuálně obeslat všechny své dlužníky s potřebnými informacemi?",
      "gist": "Odpůrci obesílání dlužníků říkají, že se o své dluhy mají starat hlavně sami. Zastánci tvrdí, že by město mělo aktivně usilovat, aby se dlužné peníze vrátily do rozpočtu, a že osobní obeslání je účinné.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-6",
      "name": "Více kamer",
      "title": "Měly by být ve městě instalovány další kamery?",
      "gist": "Zastánci uvádějí zvýšení bezpečnosti problémových lokalit, odpůrci zdůrazňují přílišný zásah do osobních práv a přesun kriminality do jiných míst.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-7",
      "name": "Hazard zakázán",
      "title": "Jste pro úplný zákaz hazardu na území města?",
      "gist": "Příznivci zákazu argumentují sociálními problémy plynoucími z hazardu. Odpůrci zmiňují svobodu podnikání a finance, které město získá na daních.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-8",
      "name": "MHD zdarma",
      "title": "Měla by být městská hromadná doprava pro všechny rezidenty zdarma?",
      "gist": "Zastánci zrušení jízdného argumentují zlepšením životního prostředí, zklidnění dopravy i úsporami za tisk lístků nebo vedení agendy s vymáháním dlužného jízdného. Odpůrci tvrdí, že se jedná o nehospodárné nakládání s veřejnými prostředky. Podle jiných by to příliš zatížilo městský rozpočet.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-9",
      "name": "Bezbariérové zastávky MHD",
      "title": "Město by mělo více investovat do zastávek hromadné dopravy, aby byly až na výjimky bezbariérové.",
      "gist": "",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-10",
      "name": "Jmenovité výsledky hlasování zastupitelstva",
      "title": "Hlasování členů zastupitelstva města se má zveřejňovat jmenovitě.",
      "gist": "Podle zastánců je pro veřejnou kontrolu důležité vidět, jak přesně kdo v zastupitelstvu města hlasuje. Kritici to považují za zbytečné.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-11",
      "name": "Jmenovité výsledky hlasování rady",
      "title": "Hlasování členů rady města se má zveřejňovat jmenovitě.",
      "gist": "Podle zastánců je pro veřejnou kontrolu důležité vidět, jak přesně kdo v radě města hlasuje. Kritici to považují za zbytečné.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-12",
      "name": "Regulace zábavní pyrotechniky",
      "title": "Používání zábavní pyrotechniky jindy než na Silvestra má být ve městě zakázané.",
      "gist": "V případě neregulace bývají problematické hlavně letní měsíce, kdy jsou ohňostroje součástí řady domácích oslav.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-13",
      "name": "Přístupné veřejné budovy v chladnu",
      "title": "Město by v topné sezóně mělo zpřístupnit některé veřejné budovy lidem jen pro zahřátí.",
      "gist": "Některá evropská města zvažují, že veřejnosti zpřístupní knihovny, komunitní centra či umělecké galerie, aby se zde mohli v nadcházející zimě zahřát ti, kdo si nemohou dovolit vytápět své domovy.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-14",
      "name": "Úspora energií – světelná výzdoba",
      "title": "Kvůli úspoře energií by město mělo omezovat noční nasvícení kulturních památek.",
      "gist": "",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-15",
      "name": "Úspora energií – veřejné osvětlení",
      "title": "Má město kvůli úspoře energií omezovat veřejné osvětlení?",
      "gist": "Kvůli energetické krizi řada měst v Rakousku, Německu, Francii a Itálii omezuje pouliční osvětlení, některé obce ho v noci vypnou úplně. Vypnutí světel na tři a půl hodiny každou noc má snížit spotřebu energie cca o čtvrtinu. Kritici namítají, že se zhorší bezpečnost ve městě.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-16",
      "name": "Úspora energií – omezení vytápění",
      "title": "V topné sezóně by se mělo omezit vytápění v městských budovách.",
      "gist": "Např. v sousedním Německu nyní plánují, že veřejné budovy se až na výjimky (např. školy) budou z důvodu úspor energie vytápět max. na 19 C.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-17",
      "name": "Konec dětských exekucí",
      "title": "Souhlasím, aby město plošně odpouštělo dluhy dětským dlužníkům a nechalo zastavit jejich exekuce.",
      "gist": "Jedná se zpravidla o historické dluhy. Dnes již dětem u města obvykle dluhy nevznikají, zodpovídají za ně např. rodiče.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-18",
      "name": "Městské transparentní účty",
      "title": "Má mít město transparentní účty, do kterých lze veřejně nahlížet?",
      "gist": "Zastánci uvádějí nutnost kontroly toho, jak město s penězi nakládá. Odpůrci se domnívají, že je to komplikované a že hrozí únik osobních údajů.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-19",
      "name": "Participativní rozpočet",
      "title": "O části rozpočtu města mají mít možnost rozhodovat občané přímo.",
      "gist": "Jde např. o participativní rozpočet: radnice vymezí část peněz z ročního rozpočtu, občané pak podávají návrhy, co by se za tyto peníze mělo ve městě v následujícím roce vylepšit a vítězné projekty se poté realizují.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-20",
      "name": "Zvýšení počtu městských bytů",
      "title": "Město by mělo zvyšovat počty bytů ve svém vlastnictví.",
      "gist": "Některá města se snaží o odkup nebo výstavbu bytů do svého vlastnictví. Důvodem mj. je, že se jim nedostává bytů pro lékaře a zdravotní sestry, policisty, učitele či seniory a potřebné. Kritici namítají, že údržba městských bytů zatěžuje rozpočet.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-21",
      "name": "Omezení vánoční výzdoby",
      "title": "Město by mělo kvůli rostoucím cenám energie omezit veřejné slavnostní osvětlení v době Vánoc.",
      "gist": "K podobnému kroku přistoupila například rakouská Vídeň. Na hlavním bulváru Ring kolem centra nebude vánoční osvětlení vůbec, na dalších místech se bude rozsvěcet o hodinu později než doposud.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-22",
      "name": "Obědy zdarma",
      "title": "Ve všech veřejných základních školách na území města by měly mít děti možnost obědvat zdarma.",
      "gist": "Podle průzkumů žije 20 procent českých dětí v ohrožení příjmovou chudobou. Některé děti již dostávají obědy zdarma díky několika různým projektům, závisí to ale na vůli školy a města, zda se do takových projektů zapojí.",
      "detail": "",
      "tags": []
    },
    {
      "id": "komunalni-2022-569810-question-23",
      "name": "Sdílení aut",
      "title": "Je třeba, aby město podporovalo sdílení aut (tzv. carsharing).",
